version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=monitoring
      - DB_PORT=5432
      - TZ=UTC
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=monitoring
      - TZ=UTC
