# Use an official Python image as the base
FROM python:3.9-slim-buster AS base

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements/base.txt requirements/prod.txt ./
RUN pip install --no-cache-dir -r base.txt -r prod.txt

# Copy application code
COPY . .

# Final stage for production
FROM base AS production

# Expose the application port
EXPOSE 8000

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]